### ISSUE TITLE
Upload not possible with fineuploader

### ISSUE THREAD

**Issue by inndividuell** [terminal42/contao-avatar#19]
Contao 4.9.1
When in FE and trying to upload a image following error appears in console:

[Fine Uploader 5.0.2] Error when attempting to parse xhr response text (Unexpected token < in JSON at position 0)

I think thats a general Problem with fine uploader....or do i have to configure something?

**Comment by qzminski** [comment]
Please check logs in Contao backend as well as in the `/var/logs/` folder.

**Comment by SGehle** [comment]
I have the same problem. No entry in /var/logs/

**Comment by SGehle** [comment]
The executePostActions Hook is not fired

**Comment by Cleanerrr** [comment]
Hi everybody,
I have the same problem, or similar. When I try to upload member Avatar in the registration form, every time I have the same message: "Upload fehlgeschlagen".
I tried to change Avatar setting in Contao backend, and also settings for files uploading, but the problem is still here. I also don't have any log message in the log file.

**Comment by Cleanerrr** [comment]
Anyone some solution/suggestion/hint for this problem?

**Comment by qzminski** [comment]
The fix should be available in 1.3.1. Please note that the avatar will not work if you have multiple registration or personal data modules on the same page. 

Related issue: https://github.com/contao/core-bundle/issues/1493
